/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ./static/Character.glb 
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/Character.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="AuxScene">
        <group name="Scene">
          <group name="rp_eric_rigged_001" position={[0, 0, 0.522]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <primitive object={nodes.neck} />
            <skinnedMesh name="rp_eric_rigged_001_geo" geometry={nodes.rp_eric_rigged_001_geo.geometry} material={materials.rp_eric_rigged_001_mat} skeleton={nodes.rp_eric_rigged_001_geo.skeleton} />
          </group>
          <group name="rig" position={[0, 0, 0.545]} scale={0.962}>
            <primitive object={nodes.root} />
            <primitive object={nodes['MCH-torsoparent']} />
            <primitive object={nodes['MCH-hand_ikparentL']} />
            <primitive object={nodes['MCH-upper_arm_ik_targetparentL']} />
            <primitive object={nodes['MCH-hand_ikparentR']} />
            <primitive object={nodes['MCH-upper_arm_ik_targetparentR']} />
            <primitive object={nodes['MCH-foot_ikparentL']} />
            <primitive object={nodes['MCH-thigh_ik_targetparentL']} />
            <primitive object={nodes['MCH-foot_ikparentR']} />
            <primitive object={nodes['MCH-thigh_ik_targetparentR']} />
            <skinnedMesh name="rp_eric_rigged_001_geo001" geometry={nodes.rp_eric_rigged_001_geo001.geometry} material={materials.rp_eric_rigged_001_mat} skeleton={nodes.rp_eric_rigged_001_geo001.skeleton} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Character.glb')
