/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ./static/eric.glb 
*/

import React, { useRef } from 'react'
import { useGLTF, PerspectiveCamera } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/eric.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[0.107, 0.487, -63.492]}>
          <mesh geometry={nodes.Mesh.geometry} material={materials.rp_eric_rigged_001_mat} position={[0, 0, 52.162]} />
          <mesh geometry={nodes.Mesh004.geometry} material={materials.rp_eric_rigged_001_mat} position={[0, 0, 52.176]} />
        </group>
      </group>
      <PerspectiveCamera makeDefault={false} far={652.528} near={541.076} fov={39.598} position={[1.728, 2.57, 5.491]} rotation={[-0.285, 0.218, 0.063]} scale={0.01} />
    </group>
  )
}

useGLTF.preload('/eric.glb')
