/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./static/realisticCharacter.glb
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function RealisticCharacter(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/realisticCharacter.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="rp_eric_rigged_001" position={[0.01, 0, 0.52]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.neck} />
          <skinnedMesh name="rp_eric_rigged_001_geo" geometry={nodes.rp_eric_rigged_001_geo.geometry} material={materials.rp_eric_rigged_001_mat} skeleton={nodes.rp_eric_rigged_001_geo.skeleton} />
        </group>
        <group name="rig" position={[0, 0, 0.55]} scale={0.96}>
          <primitive object={nodes.root} />
          <primitive object={nodes['MCH-torsoparent']} />
          <primitive object={nodes['MCH-hand_ikparentL']} />
          <primitive object={nodes['MCH-upper_arm_ik_targetparentL']} />
          <primitive object={nodes['MCH-hand_ikparentR']} />
          <primitive object={nodes['MCH-upper_arm_ik_targetparentR']} />
          <primitive object={nodes['MCH-foot_ikparentL']} />
          <primitive object={nodes['MCH-thigh_ik_targetparentL']} />
          <primitive object={nodes['MCH-foot_ikparentR']} />
          <primitive object={nodes['MCH-thigh_ik_targetparentR']} />
          <skinnedMesh name="rp_eric_rigged_001_geo001" geometry={nodes.rp_eric_rigged_001_geo001.geometry} material={materials.rp_eric_rigged_001_mat} skeleton={nodes.rp_eric_rigged_001_geo001.skeleton} />
        </group>
        <group name="WGT-rig_spine_fk" position={[0, 1.16, -0.02]} rotation={[1.82, 0, 0]} scale={0.15} />
        <group name="WGT-rig_spine_fk001" position={[0, 1.29, 0]} rotation={[1.69, 0, 0]} scale={0.14} />
        <group name="WGT-rig_spine_fk002" position={[0, 1.29, 0]} rotation={[1.54, 0, 0]} scale={0.17} />
        <group name="WGT-rig_spine_fk003" position={[0, 1.47, -0.01]} rotation={[1.54, 0, 0]} scale={0.19} />
        <group name="WGT-rig_tweak_spine" position={[0, 1.01, -0.06]} rotation={[1.82, 0, 0]} scale={0.08} />
        <group name="WGT-rig_tweak_spine001" position={[0, 1.16, -0.02]} rotation={[1.69, 0, 0]} scale={0.07} />
        <group name="WGT-rig_tweak_spine002" position={[0, 1.29, 0]} rotation={[1.54, 0, 0]} scale={0.09} />
        <group name="WGT-rig_tweak_spine003" position={[0, 1.47, -0.01]} rotation={[1.54, 0, 0]} scale={0.1} />
        <group name="WGT-rig_tweak_spine004" position={[0, 1.66, -0.01]} rotation={[1.54, 0, 0]} scale={0.1} />
        <group name="WGT-rig_torso" position={[0, 1.08, -0.04]} scale={0.39} />
        <group name="WGT-rig_hips" position={[0, 1.01, -0.06]} rotation={[1.82, 0, 0]} scale={0.16} />
        <group name="WGT-rig_chest" position={[0, 1.47, -0.01]} rotation={[1.54, 0, 0]} scale={0.22} />
        <group name="WGT-rig_breastL" position={[0.1, 1.5, -0.05]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.14} />
        <group name="WGT-rig_breastR" position={[-0.1, 1.5, -0.05]} rotation={[0, 0, -Math.PI]} scale={-0.14} />
        <group name="WGT-rig_shoulderL" position={[0.02, 1.61, 0.07]} rotation={[0, -1.04, 0]} scale={0.18} />
        <group name="WGT-rig_upper_arm_parentL" position={[0.19, 1.59, -0.03]} rotation={[-1.57, -0.66, -2.67]} scale={0.06} />
        <group name="WGT-rig_upper_arm_fkL" position={[0.19, 1.59, -0.03]} rotation={[-1.57, -0.66, -2.67]} scale={0.24} />
        <group name="WGT-rig_forearm_fkL" position={[0.33, 1.4, -0.03]} rotation={[-2.07, -0.79, -3.01]} scale={0.34} />
        <group name="WGT-rig_hand_fkL" position={[0.57, 1.19, 0.09]} rotation={[-2.1, -0.42, -3.01]} scale={0.1} />
        <group name="WGT-rig_upper_arm_ikL" position={[0.19, 1.59, -0.03]} rotation={[-1.57, -0.66, -2.67]} scale={0.24} />
        <group name="WGT-rig_upper_arm_ik_targetL" position={[0.21, 1.14, -0.52]} rotation={[2.66, -0.21, 0.81]} scale={0.07} />
        <group name="WGT-rig_hand_ikL" position={[0.57, 1.19, 0.09]} rotation={[-2.1, -0.42, -3.01]} scale={0.1} />
        <group name="WGT-rig_VIS_upper_arm_ik_poleL" position={[0.33, 1.4, -0.03]} rotation={[Math.PI / 2, 0, -1.78]} scale={0.56} />
        <group name="WGT-rig_upper_arm_tweakL" position={[0.19, 1.59, -0.03]} rotation={[-1.57, -0.66, -2.67]} scale={0.06} />
        <group name="WGT-rig_upper_arm_tweakL001" position={[0.26, 1.49, -0.03]} rotation={[-1.57, -0.66, -2.67]} scale={0.06} />
        <group name="WGT-rig_forearm_tweakL" position={[0.33, 1.4, -0.03]} rotation={[-2.07, -0.79, -3.01]} scale={0.09} />
        <group name="WGT-rig_forearm_tweakL001" position={[0.45, 1.3, 0.03]} rotation={[-2.07, -0.79, -3.01]} scale={0.09} />
        <group name="WGT-rig_hand_tweakL" position={[0.57, 1.19, 0.09]} rotation={[-2.1, -0.42, -3.01]} scale={0.03} />
        <group name="WGT-rig_shoulderR" position={[-0.02, 1.61, 0.07]} rotation={[3.14, -1.04, 0]} scale={-0.18} />
        <group name="WGT-rig_upper_arm_parentR" position={[-0.19, 1.59, -0.03]} rotation={[1.57, -0.66, -2.67]} scale={-0.06} />
        <group name="WGT-rig_upper_arm_fkR" position={[-0.19, 1.59, -0.03]} rotation={[1.57, -0.66, -2.67]} scale={-0.24} />
        <group name="WGT-rig_forearm_fkR" position={[-0.33, 1.4, -0.03]} rotation={[1.07, -0.79, -3.01]} scale={-0.34} />
        <group name="WGT-rig_hand_fkR" position={[-0.57, 1.19, 0.09]} rotation={[1.04, -0.42, -3.01]} scale={-0.1} />
        <group name="WGT-rig_upper_arm_ikR" position={[-0.19, 1.59, -0.03]} rotation={[1.57, -0.66, -2.67]} scale={-0.24} />
        <group name="WGT-rig_upper_arm_ik_targetR" position={[-0.21, 1.14, -0.52]} rotation={[-0.48, -0.21, 0.81]} scale={-0.07} />
        <group name="WGT-rig_hand_ikR" position={[-0.57, 1.19, 0.09]} rotation={[1.04, -0.42, -3.01]} scale={-0.1} />
        <group name="WGT-rig_VIS_upper_arm_ik_poleR" position={[-0.33, 1.4, -0.03]} rotation={[-Math.PI / 2, 0, -1.78]} scale={-0.56} />
        <group name="WGT-rig_upper_arm_tweakR" position={[-0.19, 1.59, -0.03]} rotation={[1.57, -0.66, -2.67]} scale={-0.06} />
        <group name="WGT-rig_upper_arm_tweakR001" position={[-0.26, 1.49, -0.03]} rotation={[1.57, -0.66, -2.67]} scale={-0.06} />
        <group name="WGT-rig_forearm_tweakR" position={[-0.33, 1.4, -0.03]} rotation={[1.07, -0.79, -3.01]} scale={-0.09} />
        <group name="WGT-rig_forearm_tweakR001" position={[-0.45, 1.3, 0.03]} rotation={[1.07, -0.79, -3.01]} scale={-0.09} />
        <group name="WGT-rig_hand_tweakR" position={[-0.57, 1.19, 0.09]} rotation={[1.04, -0.42, -3.01]} scale={-0.03} />
        <group name="WGT-rig_thigh_parentL" position={[0.1, 1.07, -0.01]} rotation={[-1.59, 0, 0]} scale={0.13} />
        <group name="WGT-rig_thigh_fkL" position={[0.1, 1.07, -0.01]} rotation={[-1.59, 0, 0]} scale={0.53} />
        <group name="WGT-rig_shin_fkL" position={[0.1, 0.54, 0]} rotation={[-1.47, 0, 0]} scale={0.45} />
        <group name="WGT-rig_foot_fkL" position={[0.1, 0.09, -0.05]} rotation={[-2.59, 0, 0]} scale={0.16} />
        <group name="WGT-rig_toe_fkL" position={[0.1, 0, 0.09]} rotation={[Math.PI, 0, Math.PI]} scale={0.07} />
        <group name="WGT-rig_thigh_ikL" position={[0.1, 1.07, -0.01]} rotation={[-1.59, 0, 0]} scale={0.53} />
        <group name="WGT-rig_thigh_ik_targetL" position={[0.1, 0.5, 0.98]} rotation={[0.03, 0, 0]} scale={0.12} />
        <group name="WGT-rig_foot_ikL" position={[0.1, 0.09, -0.05]} scale={0.16} />
        <group name="WGT-rig_VIS_thigh_ik_poleL" position={[0.1, 0.54, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.99} />
        <group name="WGT-rig_thigh_tweakL" position={[0.1, 1.07, -0.01]} rotation={[-1.59, 0, 0]} scale={0.13} />
        <group name="WGT-rig_thigh_tweakL001" position={[0.1, 0.8, -0.01]} rotation={[-1.59, 0, 0]} scale={0.13} />
        <group name="WGT-rig_shin_tweakL" position={[0.1, 0.54, 0]} rotation={[-1.47, 0, 0]} scale={0.11} />
        <group name="WGT-rig_shin_tweakL001" position={[0.1, 0.31, -0.02]} rotation={[-1.47, 0, 0]} scale={0.11} />
        <group name="WGT-rig_foot_tweakL" position={[0.1, 0.09, -0.05]} rotation={[-2.59, 0, 0]} scale={0.04} />
        <group name="WGT-rig_foot_spin_ikL" position={[0.1, 0, 0.09]} scale={0.08} />
        <group name="WGT-rig_foot_heel_ikL" position={[0.1, 0.09, -0.05]} scale={0.08} />
        <group name="WGT-rig_toe_ikL" position={[0.1, 0, 0.09]} rotation={[Math.PI, 0, Math.PI]} scale={0.07} />
        <group name="WGT-rig_thigh_parentR" position={[-0.1, 1.07, -0.01]} rotation={[1.55, 0, 0]} scale={-0.13} />
        <group name="WGT-rig_thigh_fkR" position={[-0.1, 1.07, -0.01]} rotation={[1.55, 0, 0]} scale={-0.53} />
        <group name="WGT-rig_shin_fkR" position={[-0.1, 0.54, 0]} rotation={[1.67, 0, 0]} scale={-0.45} />
        <group name="WGT-rig_foot_fkR" position={[-0.1, 0.09, -0.05]} rotation={[0.55, 0, 0]} scale={-0.16} />
        <group name="WGT-rig_toe_fkR" position={[-0.1, 0, 0.09]} rotation={[0, 0, -Math.PI]} scale={-0.07} />
        <group name="WGT-rig_thigh_ikR" position={[-0.1, 1.07, -0.01]} rotation={[1.55, 0, 0]} scale={-0.53} />
        <group name="WGT-rig_thigh_ik_targetR" position={[-0.1, 0.5, 0.98]} rotation={[-3.11, 0, 0]} scale={-0.12} />
        <group name="WGT-rig_foot_ikR" position={[-0.1, 0.09, -0.05]} rotation={[-Math.PI, 0, 0]} scale={-0.16} />
        <group name="WGT-rig_VIS_thigh_ik_poleR" position={[-0.1, 0.54, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={-0.99} />
        <group name="WGT-rig_thigh_tweakR" position={[-0.1, 1.07, -0.01]} rotation={[1.55, 0, 0]} scale={-0.13} />
        <group name="WGT-rig_thigh_tweakR001" position={[-0.1, 0.8, -0.01]} rotation={[1.55, 0, 0]} scale={-0.13} />
        <group name="WGT-rig_shin_tweakR" position={[-0.1, 0.54, 0]} rotation={[1.67, 0, 0]} scale={-0.11} />
        <group name="WGT-rig_shin_tweakR001" position={[-0.1, 0.31, -0.02]} rotation={[1.67, 0, 0]} scale={-0.11} />
        <group name="WGT-rig_foot_tweakR" position={[-0.1, 0.09, -0.05]} rotation={[0.55, 0, 0]} scale={-0.04} />
        <group name="WGT-rig_foot_spin_ikR" position={[-0.1, 0, 0.09]} rotation={[-Math.PI, 0, 0]} scale={-0.08} />
        <group name="WGT-rig_foot_heel_ikR" position={[-0.1, 0.09, -0.05]} rotation={[-Math.PI, 0, 0]} scale={-0.08} />
        <group name="WGT-rig_toe_ikR" position={[-0.1, 0, 0.09]} rotation={[0, 0, Math.PI]} scale={-0.07} />
        <group name="WGT-rig_root" scale={1.01} />
      </group>
    </group>
  )
}

useGLTF.preload('/realisticCharacter.glb')
