/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ./static/room.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/room.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.826}>
          <group rotation={[Math.PI, 0, Math.PI]}>
            <mesh geometry={nodes.Floor002_woodFloor_0.geometry} material={materials.woodFloor} />
            <mesh geometry={nodes.Floor002_carpet_0.geometry} material={materials.carpet} />
          </group>
          <group rotation={[Math.PI, 0, Math.PI]}>
            <mesh geometry={nodes.Floor003_ceilingtiles_plain_0.geometry} material={materials.ceilingtiles_plain} />
            <mesh geometry={nodes.Floor003_ceilingtiles_0.geometry} material={materials.ceilingtiles} />
          </group>
          <group rotation={[Math.PI, 0, Math.PI]}>
            <mesh geometry={nodes.Spine_low001_SwivlChair_0.geometry} material={materials.SwivlChair} />
            <mesh geometry={nodes.Spine_low001_SwivlChair_BLACK_0.geometry} material={materials.SwivlChair_BLACK} />
          </group>
          <mesh geometry={nodes['3DGeom-1'].geometry} material={materials.SmallWindow} />
          <mesh geometry={nodes['3DGeom-2'].geometry} material={materials.Walls} />
          <mesh geometry={nodes.RoundWindowGlass001_glass_0_1.geometry} material={materials.glass} rotation={[Math.PI, 0, Math.PI]} />
          <mesh geometry={nodes.RoundWindowMetal001_Metal_Black_0_1.geometry} material={materials.Metal_Black} rotation={[Math.PI, 0, Math.PI]} />
          <mesh geometry={nodes.Doors_Door_Solid_0_1.geometry} material={materials.Door_Solid} rotation={[Math.PI, 0, Math.PI]} />
          <mesh geometry={nodes.Shelving_shelving_0_1.geometry} material={materials.shelving} rotation={[Math.PI, 0, Math.PI]} />
          <mesh geometry={nodes.ComicTable_LP001__0_1.geometry} material={materials['ComicTable_LP.001__0']} rotation={[Math.PI, 0, Math.PI]} />
          <mesh geometry={nodes.MeetingTable_New_Tabletop_Joined001_meetingTable_0_1.geometry} material={materials.meetingTable} rotation={[Math.PI, 0, Math.PI]} />
          <mesh geometry={nodes.BrownChairs_BrownChair_0_1.geometry} material={materials.BrownChair} rotation={[Math.PI, 0, Math.PI]} />
          <mesh geometry={nodes.BigWhiteTables_BigWhiteTable_0_1.geometry} material={materials.BigWhiteTable} rotation={[Math.PI, 0, Math.PI]} />
          <mesh geometry={nodes.WoodenDesks_woodenDesk_0_1.geometry} material={materials.woodenDesk} rotation={[Math.PI, 0, Math.PI]} />
          <mesh geometry={nodes.Computers_Desktop_0_1.geometry} material={materials.Desktop} rotation={[Math.PI, 0, Math.PI]} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/room.glb')
